import { DefaultTheme as NavigationDefaultTheme } from "@react-navigation/native"
import { DefaultTheme as PaperDefaultTheme } from "react-native-paper"

export const AppColorblindTheme = {
  ...NavigationDefaultTheme,
  ...PaperDefaultTheme,
  roundness: 4,
  colors: {
    ...NavigationDefaultTheme.colors,
    ...PaperDefaultTheme.colors,
    primary: '#dc267f',
    accent: '#648fff',
    tertiary: "#ffb000",
    background: "#f9f9f9",
    surface: "#ffffff",
    black: "#000000",
    white: "#ffffff",
    greyscale: "#f5f5f5",
    greyscaleDark: "#c2c2c2",
    colorblockBlue: "#648fff",
    colorblockBlueDark: "#1d62cb",
    colorblockBlueLight: "#9cbfff",
    colorblockRed: "#dc267f",
    colorblockRedDark: "#a50053", 
    colorblockRedLight: "#ff63ae",
    colorblockYellow: "#ffb000",
    colorblockYellowDark: "#ffe24b",
    colorblockYellowLight: "#c68100",
    diztroBlue: "#0080ff",
    diztroBlueDark: "#0055cb",
    diztroBlueLight: "#69afff",
    diztroGreen: "#009e73",
    diztroGreenDark: "#006e47",
    diztroGreenLight: "#52d0a2",
    diztroOrange: "#fe6100",
    diztroOrangeDark: "#c32d00",
    diztroOrangeLight: "#ff933e",
    diztroPink: "#dc267f",
    diztroPinkDark: "#a50053", 
    diztroPinkLight: "#ff63ae",
    diztroPurple: "#785ef0",
    diztroPurpleDark: "#3f32bc",
    diztroPurpleLight: "#ae8cff",
    diztroYellow: "#ffb000",
    diztroYellowDark: "#ffe24b",
    diztroYellowLight: "#c68100",
    stripeActiveOutline: "#c4d6e9",
    stripeOutline: "#e6e6e6",
  },
};