import { DefaultTheme as NavigationDefaultTheme } from "@react-navigation/native"
import { DefaultTheme as PaperDefaultTheme } from "react-native-paper"

export const AppDefaultTheme = {
  ...NavigationDefaultTheme,
  ...PaperDefaultTheme,
  roundness: 4,
  colors: {
    ...NavigationDefaultTheme.colors,
    ...PaperDefaultTheme.colors,
    primary: '#ff4248',
    accent: '#3059ff',
    tertiary: "#ffdc14",
    background: "#f9f9f9",
    surface: "#ffffff",
    black: "#000000",
    white: "#ffffff",
    greyscale: "#f5f5f5",
    greyscaleDark: "#c2c2c2",
    colorblockBlue: "#3059ff",
    colorblockBlueLight: "#7a86ff",
    colorblockBlueDark: "#0030cb",
    colorblockRed: "#ff4248",
    colorblockRedDark: "#c40020", 
    colorblockRedLight: "#ff7974",
    colorblockYellow: "#ffdc14",
    colorblockYellowDark: "#c7ab00",
    colorblockYellowLight: "#ffff59",
    diztroBlue: "#0080ff",
    diztroBlueDark: "#0055cb",
    diztroBlueLight: "#69afff",
    diztroGreen: "#00bf00",
    diztroGreenDark: "#008d00",
    diztroGreenLight: "#5ff349",
    diztroOrange: "#ff8000",
    diztroOrangeDark: "#c55100",
    diztroOrangeLight: "#ffb143",
    diztroPink: "#ff80ff",
    diztroPinkDark: "#ca4dcb",
    diztroPinkLight: "#ffb3ff",
    diztroPurple: "#8c00bf",
    diztroPurpleDark: "#58008e",
    diztroPurpleLight: "#c149f3",
    diztroYellow: "#ffff00",
    diztroYellowDark: "#c7cc00",
    diztroYellowLight: "#ffff5a",
    stripeActiveOutline: "#c4d6e9",
    stripeOutline: "#e6e6e6",
  },
};