import { DarkTheme as NavigationDarkTheme } from "@react-navigation/native"
import { DarkTheme as PaperDarkTheme } from "react-native-paper"

export const AppDarkTheme = {
  ...NavigationDarkTheme,
  ...PaperDarkTheme,
  roundness: 4,
  colors: {
    ...NavigationDarkTheme.colors,
    ...PaperDarkTheme.colors,
    primary: '#c40020',
    accent: '#0030cb',
    tertiary: "#c7ab00",
    background: "#181818",
    surface: "#212121",
    black: "#000000",
    white: "#ffffff",
    greyscale: "#5a5a5a",
    greyScaleDark: "#313131",
    colorblockBlue: "#3059ff",
    colorblockBlueLight: "#7a86ff",
    colorblockBlueDark: "#0030cb",
    colorblockRed: "#ff4248",
    colorblockRedDark: "#c40020", 
    colorblockRedLight: "#ff7974",
    colorblockYellow: "#ffdc14",
    colorblockYellowDark: "#c7ab00",
    colorblockYellowLight: "#ffff59",
    diztroBlue: "#0080ff",
    diztroBlueDark: "#0055cb",
    diztroBlueLight: "#69afff",
    diztroGreen: "#00bf00",
    diztroGreenDark: "#008d00",
    diztroGreenLight: "#5ff349",
    diztroOrange: "#ff8000",
    diztroOrangeDark: "#c55100",
    diztroOrangeLight: "#ffb143",
    diztroPink: "#ff80ff",
    diztroPinkDark: "#ca4dcb",
    diztroPinkLight: "#ffb3ff",
    diztroPurple: "#8c00bf",
    diztroPurpleDark: "#58008e",
    diztroPurpleLight: "#c149f3",
    diztroYellow: "#ffff00",
    diztroYellowDark: "#c7cc00",
    diztroYellowLight: "#ffff5a",
    stripeActiveOutline: "#c4d6e9",
    stripeOutline: "#e6e6e6",
  },
};